name: Build DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc

      - name: Fetch Dependencies
        run: cargo fetch --target i686-pc-windows-msvc

      - name: Patch Detour for 32-bit Target
        shell: pwsh
        run: |
          Get-ChildItem -Path "$env:USERPROFILE\.cargo\registry\src" -Filter "macros.rs" -Recurse | ForEach-Object {
            (Get-Content $_.FullName) -replace 'extern "win64"', 'extern "C"' | Set-Content $_.FullName
          }

      - name: Build 32-bit DLL
        run: cargo build --release --target i686-pc-windows-msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uplay_r1_loader_x86
          path: target/i686-pc-windows-msvc/release/*.dll
