name: Build DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc

      - name: Fetch Dependencies
        run: cargo fetch --target i686-pc-windows-msvc

      - name: Fix Detour Macro for x86
        shell: pwsh
        run: |
          $file = Get-ChildItem -Path "$env:USERPROFILE\.cargo\registry\src" -Filter "macros.rs" -Recurse | Where-Object { $_.FullName -like "*detour-0.8.1*" } | Select-Object -First 1
          if ($file) {
            $content = Get-Content $file.FullName -Raw
            # Comentar las líneas de win64 para evitar conflictos en 32-bit
            $fixed = $content -replace 'impl_hookable!\(@impl_pair \(\(\$(\w+) : \$ty\),\*\) \(extern "win64"', '/* impl_hookable!(@impl_pair (($$1 : $$ty),*) (extern "win64"'
            $fixed = $fixed -replace '(\(extern "win64" fn\(\(\$(\w+)\),\*\) -> Ret\)\);)', '$$1 */'
            Set-Content -Path $file.FullName -Value $fixed -NoNewline
          }

      - name: Build 32-bit DLL
        run: cargo build --release --target i686-pc-windows-msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uplay_r1_loader_x86
          path: target/i686-pc-windows-msvc/release/*.dll
